---
- name: deploy to tomcat
  hosts: web
  become: yes
  tasks: 
    - name: copy war file in tomcat
      src: "/var/snap/jenkins/4874/workspace/shatansible/target/shatansible.war"
      dest: "/opt/tomcat/webapps/shatansible.war"
      remote_src: no
     
